### ISSUE TITLE
osu! touch input doesn't always behave as expected

### ISSUE THREAD

**Issue by dokkkku** [ppy/osu#22556]
### Type

Game behaviour

### Bug description

https://user-images.githubusercontent.com/66845810/217566875-385766d2-ecc6-450b-9ba0-5e6d4e23e416.mp4

(Sorry for the bad quality)

To be short: Lazer doesn't know which input is supposed to be which. Im trying to drag and click with my other fingers, but at the start of the map, it just doesn't know which is which. It happens occasionally during gameplay aswell, leading to missing or failing.

### Version

2023.207.0-Lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10686885/database.log)
[network.log](https://github.com/ppy/osu/files/10686886/network.log)
[performance.log](https://github.com/ppy/osu/files/10686887/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10686888/runtime.log)

**Comment by JeromTWinL** [comment]
Happened to me, to play for now partially (with tap streaming)

First touch should be in an object.

If you released your finger in break time (or starting), click on an object (circle, slider) and lazer will detect it as cursor, that's how it coded (mentioned in changelog video)

**Comment by bdach** [comment]
I'm not entirely sure what I'm looking at, but are you tapping with one hand, and following the objects with the other hand, but *also* lifting the other hand as you're following the objects?

That can't really work with the way we have implemented things. As things stand, the "following" touch must be continuous. As in you can't lift it, you need to keep it pressed all the time while you're following the objects.

I'm not sure it can work any other way. If we did anything to "detect" which touch is the "object" touch based on positioning, then you could just spam touches all over and have one of them register as a hit.

**Comment by Naozumi520** [comment]
I mentioned the same problem in the release video, but seems peppy didn’t saw my update comments with video.

https://youtu.be/IKDoMMlPTr4

So far I have to not touch the screen until the first note appears, otherwise it doesn't recognize drag and touch. I'm sure what has been implemented works fine, but for some reason it doesn't work until the first note.

> https://youtu.be/IKDoMMlPTr4
The first attempt was when my pen on the screen before note appeared, and the second attempt was when I didn’t drag and touch before I saw the first note.

This problem also seems to exist with the relax mod. When you drag before the first note appears, it won't click!

This two problems exists on both of my iPhone and iPad.

**Comment by dokkkku** [comment]
> 

I first tried to drag with my right index and tap with my other 2 fingers. It detected the other 2 fingers as cursor inputs even though my right finger was already pressed.

On the second try, i tried tapping the notes first (not dragging, just tapping) and then started dragging with clicking. It worked for a moment,  but then the other 2 inputs (the ones clicking, not dragging) get recognized as cursor inputs. 

sorry i can't explain it better or more accurately.

**Comment by JeromTWinL** [comment]
@dokkkku you're right, even if i clicked on the object and drag it to objects, the cursor goes to tap-streaming (clicking) finger area in touch screen (that really disappointed me), so I play it just like normally clicking the objects (before 2023.207.0 update), I thought it could be my phone performance, so I took my performance tablet (Xiaomi Pad 5) and installed osu!lazer, it still happened.

**Comment by JeromTWinL** [comment]
This isn't an issue i guess (cuz it's because if we clicked when cursor isn't in an object, click area will be detected as cursor), but this makes "if you leave a mistake, you should drag it again from an object."

**Comment by Naozumi520** [comment]
> This isn't an issue i guess (it's because if we clicked when cursor isn't in an object, click area will be detected as cursor), but this makes "if you leave a mistake, you should drag it again from an object to continue play" In touch devices.

What did you mean isn't an issue? For me I can't drag the cursor anyway when I clicked. The moment that I pressed with two other fingers it unregistered my Apple Pencil as cursor to touch but two fingers as the cursor. But what peppy say is as soon as we tap the screen then the finger will no longer be detected as holding and the two other fingers will registers as click. There must be something wrong, obviously.

**Comment by JeromTWinL** [comment]
> > This isn't an issue i guess (it's because if we clicked when cursor isn't in an object, click area will be detected as cursor).
> 
> What did you mean isn't an issue? For me I can't drag the cursor anyway when I clicked. The moment that I pressed with two other fingers it unregistered my Apple Pencil as cursor to touch but two fingers as the cursor. But what peppy say is as soon as we tap the screen then the finger will no longer be detected as holding and the two other fingers will registers as click. There must be something wrong, obviously.
> 
> > but this makes "if you leave a mistake, you should drag it again from an object to continue play" In touch devices.
> 
> So far, no one has made a mistake here. You can see the OP's video and my video start over with the finger on the screen the whole time.

As i already told "i guess" I'm not sure if it's my fault to be missed away

**Comment by JeromTWinL** [comment]
I carefully watched @dokkkku's video, at 0:19 his click didn't got recognised and detected the click as cursor (slider number: 1) as proof, there's no slider follow circle in that slider.

**Comment by Naozumi520** [comment]
Yes. It's definitely an issue, and we've been talking about it. Try to drag with relax mod. If you hold the screen before the first note appeared there may have a chance that the relax mod stopped working.

**Comment by Naozumi520** [comment]
https://user-images.githubusercontent.com/52615455/219061846-8896302c-ecb8-4214-a9dc-6e453e7d205a.mp4

Recorded a video again, but using my phone in this time (iPhone 13 Pro), and the same thing happened.

**Comment by JeromTWinL** [comment]
The fix is to have a "empty" tap streaming area with border line (to let users note which is which).Which shouldn't be detected as cursor, should be detected as "click" action. Just like osu!droid (left side tap streaming area with border) as mentioned in #4201

**Comment by Naozumi520** [comment]
> The fix is to have a "empty" tap streaming area with border line (to let users note which is which).Which shouldn't be detected as cursor, should be detected as "click" action. Just like osu!droid. (left side tap streaming area with border)

I'm not sure if it will work cuz the touch implementation actually works, but touching before the first note makes it detect wrong (for me), which is something need to be improved. So idk if it's a good idea to change how two-fingers touch is implemented.

**Comment by JeromTWinL** [comment]
> I'm not sure if it will work cuz the touch implementation actually works, but touching before the first note makes it detect wrong (for me)
Touching before the first note won't detect wrong for you only, cuz it was coded like "objects = cursor" and "no objects = not cursor" if we started clicking (or dragging cursor) the cursor dragging finger will be cancelled by the clicking finger (and detect clicking finger as cursor), if you had click the first note with cursor finger, the clicking finger won't cancel the cursor (won't pull away the cursor from the cursor dragging finger), as you keep holding the cursor dragging finger on the touch screen. If you took away your cursor dragging finger (in the break time), then you should click the first note and continue dragging your finger,

Even after I just read the changelog that "side tapping feature" i tried it (after updating osu!lazer)  it didn't work as I expected, and I decided to view the changelog video, they mentioned "object = cursor" that's how I understand that clicking/dragging before the first note appear won't detect it as permanent cursor, instead it will get pulled by clicking finger.

So no possibilities that you can play like osu!droid player

**Comment by Naozumi520** [comment]
> So no possibilities that you can play like osu!droid player. (dragging before first note)

I see. If that's how it's implemented, there's really nothing wrong with it. I can just tap the first note then click with two fingers as you said. But I still wish I could play exactly like osu!droid.

**Comment by NiceAesth** [comment]
This also happens during a play which can cause random fails if you ever release input while playing as it will start inputting movement from tapping. As it stands, I've found the feature to be a cool gimmick but far from usable.

**Comment by dumbuz** [comment]
This problem would be prevented by only intending you to click OUTSIDE the playfield, which most people would do anyway. <sup>[Source: trust me bro]</sup>
Touches outside the playfield shouldn't be counted as direct touches in my opinion, but this would cause problems with people who haven't memorized their playfield exactly being confused when some inputs seemingly don't go through.

This is really difficult to make understandable almost immediately.
My only idea to make this visually clear is to show the playfield border before the map starts with text inside of it that says something like "cursor tracking" and outside the playfield border that says "button clicking"

**Comment by dumbuz** [comment]
> This also happens during a play which can cause random fails if you ever release input (can happen with an apple pencil even if you don't physically lift it!)

This does happen on my 2018 iPad Pro. It seems that Apple Pencils really do not like long strokes like what's needed to play osu!

**Comment by frenzibyte** [comment]
Is there anything left to address here? Besides maybe making the touch input mapper handle touches prepared before gameplay is started (but that part is probably gonna land in `PassThroughInputManager` territory and into discussions that I think I'm better off not being in).

**Comment by peppy** [comment]
If you think the issues are fixed, I'd close for now and wait for people to report any remaining issues.

**Comment by frenzibyte** [comment]
From my testing I would say so 👌🏻
