### ISSUE TITLE
Score leaderboard doesn't make any sense

### ISSUE THREAD

**Issue by Kiryonn** [ppy/osu#23830]
### Type

Game behaviour

### Bug description

There are several issues with the leaderboard and the score system

1. Has shown in the first screenshot, there is 2 distinc rank given for unknown reasons.
2. The score itself is wrongly calculated, or at least i'm pretty sure of that. Why ? As you can see in the 2 screenshots next one to each other, i'm ranked lower than someone that as performed worse than me. And i have that issue with pretty much all songs. I'm using one where i have a full combo as an example. `It does not matter that i have normalised scores or not, the issue remains`. Proof in screens

#### `Issue 1`
![image](https://github.com/ppy/osu/assets/60699390/ef0fd24c-062d-42e2-a457-d9e58a2a880d)

#### `Issue 2`
Me ranked 40.3k | someone else ranked 27
---|---
![image](https://github.com/ppy/osu/assets/60699390/ac2bf0a7-0eb5-471d-a186-f0a293180e84) | ![image](https://github.com/ppy/osu/assets/60699390/21e5fca3-36c2-4b3c-91a3-ae7136b520ef)

Normalised scores | Non Normalised scores
---|---
![image](https://github.com/ppy/osu/assets/60699390/ab9ad1d8-fa65-4306-ae3b-133370a91a17) | ![image](https://github.com/ppy/osu/assets/60699390/f45bdc86-b687-44dd-ae9f-55e5cbe638f9)

### Version

2023.605.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/11701961/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11701963/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11701964/updater.log)
[database.log](https://github.com/ppy/osu/files/11701965/database.log)
[input.log](https://github.com/ppy/osu/files/11701966/input.log)
[network.log](https://github.com/ppy/osu/files/11701968/network.log)

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu/issues/23782

**Comment by Kiryonn** [comment]
i get that it's a duplicate with the old/new score system.
But what about my first screen that shows 2 different ranks even tho it's the exact same song/score of the song ?

**Comment by Kiryonn** [comment]
if you want i can make a separate issue for it if it's not also a duplicate

**Comment by peppy** [comment]
It's unclear what you're trying to show in the screenshot. Can you try to explain better? I can't immediately see any issue.

**Comment by Kiryonn** [comment]
I'm given 2 different ranks: 45 and 19.

**Comment by peppy** [comment]
I'm not sure about that one. You can open a separate issue to track it if you would like. It would help if you can check whether this is a freak occurrence or if you can reproduce on other beatmaps by setting new scores.

**Comment by Kiryonn** [comment]
> I'm not sure about that one. You can open a separate issue to track it if you would like. It would help if you can check whether this is a freak occurrence or if you can reproduce on other beatmaps by setting new scores.

done #23834

**Comment by Aerastus** [comment]
Was going to open a thread about this, as I believe I'm experiencing the same problem; this is mania, set a score with higher ratio, better accuracy, but the score set doesn't seem to calculate in the same way as others. This happens consistently for me:
![Untitled](https://github.com/ppy/osu/assets/138389483/c47e3894-aca6-4bb9-8151-246727dd4339)

**Comment by cooikemint** [comment]
this happens for me too, around 75% of the time i set a score on a leaderboarded map below it will say that i would be (for example) #19, but on the leaderboard i am (for example) #49 or sometimes even in the thousands. sometimes the score in local and global rankings is also different, i tried restarting the game, switching to classic score mode and it didnt fix the issue.
