### ISSUE TITLE
DeviceIOException: Unnamed product

### ISSUE THREAD

**Issue by theFox6** [ppy/osu#23872]
### Type

Game behaviour

### Bug description

This issue has been popping up since a long time ago but only since a recent update it has become a Problem.
Whenever I start Osu! or reconnect my Tablet, Osu! comes up with an Error message "DeviceIOException: Unnamed product.". However now Osu! also decides to disable the tablet because of the Error which it didn't in the past.
OTD does however run just fine and has no problems with the Tablet whatsoever.
I am using the latest release of Osu!Lazer on Linux with the Huion H950P. You can find all that in the logs too.
My OTD is built from commit `f4c859ea`.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/28263817/10a39ef6-2d3b-4021-9caa-9df8d6bdf0cf)

### Version

2023.610.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/11713434/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11713435/performance.log)
[network.log](https://github.com/ppy/osu/files/11713436/network.log)
[input.log](https://github.com/ppy/osu/files/11713437/input.log)
[database.log](https://github.com/ppy/osu/files/11713438/database.log)

**Comment by peppy** [comment]
I believe this is correct beaviour from our end and is going to require changes from OTD's end to fix your device.

If that is a non-critical issue it shouldn't be arriving to us as an error. cc/ @x9void / @infinityghost

**Comment by X9VoiD** [comment]
Will investigate.

**Comment by theFox6** [comment]
Apparently it was an issue in OTD a year ago. I'll try checking what version of OTD is actually running.

https://github.com/OpenTabletDriver/OpenTabletDriver/issues/755

**Comment by peppy** [comment]
The issue is probably that we haven't updated with a new OTD library in a while. Will need to check whether that's an issue our end or lack of nuget packages.

**Comment by theFox6** [comment]
The fix was released back in [v0.5.2](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.5.2), which was [released on nuget](https://www.nuget.org/packages/OpenTabletDriver/0.5.2) more than a year ago. The latest nuget packages seem to be on [v0.6.1](https://www.nuget.org/packages?q=opentabletdriver).

**Comment by X9VoiD** [comment]
Should already be fixed then in osu-framework/master.

**Comment by theFox6** [comment]
Apparently it was updated in https://github.com/ppy/osu-framework/commit/0688658819fd9f49c976d5b66b14c19f707cdbe2
I am getting more and more confused, why I am getting this error in the current version of lazer.

**Comment by theFox6** [comment]
So the fix should be included in [osu-framework 2021.309.0](https://github.com/ppy/osu-framework/releases/tag/2021.309.0), which should be part of lazer since last year in https://github.com/ppy/osu/commit/8fdf2b13ac2d83b206d88940e7582ae80c91a645
Yet I still get `[verbose]: ⚠️ Disabling tablet support due to error: "DeviceIOException: Unnamed product."`

**Comment by X9VoiD** [comment]
Should be fixed by [OpenTabletDriver#2820](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/2820) when it comes.

**Comment by theFox6** [comment]
> The issue is probably that we haven't updated with a new OTD library in a while. Will need to check whether that's an issue our end or lack of nuget packages.

Now it is a lack of nuget packages as a [new version of OTD](https://github.com/OpenTabletDriver/OpenTabletDriver/releases/tag/v0.6.3.0) was released.

Looking forward to playing Osu! again and thanks to @X9VoiD for fixing.
