### ISSUE TITLE
Display artifacts when playing triangles intro and beatmap videos 

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#9314]
**Describe the bug:**  
Horizontal line artifacts and heavy colour shift occurs during game launch with the triangle intro and beatmap videos (via cinema mod or background video)

**Screenshots or videos showing encountered issue:** 
Triangles intro: https://streamable.com/jzqhc6
Example beatmap video: https://streamable.com/vtt0cj
(audio capture is broken but there are no audio issues)
What the beatmap video should look like: https://www.youtube.com/watch?v=1xJbdY9B3A8

**osu!lazer version:** 2020.616.0 (shown from at least 2020.613.0)

**Logs:**
[database.log](https://github.com/ppy/osu/files/4800245/database.log)
[performance-audio.log](https://github.com/ppy/osu/files/4800248/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4800249/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4800250/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/4800251/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4800252/runtime.log)

**Comment by bdach** [comment]
Looks very similar to the artifacts in #9308, except in video sprites instead of the atlassed ones.

Can't repro so can't easily investigate, seemingly macOS-specific.

**Comment by cupppu** [comment]
I've narrowed it down to commit `f965101`, it's the first commit to have the issues

**Comment by bdach** [comment]
Yeah, very likely to be related to texture wrapping changes (ppy/osu-framework#3511).

**Comment by ryuKUNda** [comment]
Characters and images will be destroyed. OSU! is the latest version. There are no other defects.
![276F913D-6302-43FC-9374-87EF8B65558F](https://user-images.githubusercontent.com/67267826/85278847-7782c200-b4c0-11ea-8a76-a4e405ede7ba.jpeg)

**Comment by mtrower** [comment]
Poster of #9397...

> Can't repro so can't easily investigate, seemingly macOS-specific.

Doesn't happen in Windows on the same hardware, so yeah, that was my supposition as well.

I just checked my laptop (MacBook Air; vastly different hardware configuration) running 10.16 Catalina (Newer OS release).  It does *not* exhibit this bug.

I'll try to do an experimental Catalina upgrade on the desktop when I get the time for it, to control for OS release.

As it's completely reproducible on this machine, let me know if I can assist in any way.

**Comment by smoogipoo** [comment]
@mtrower Please post a screenshot of the dialog from Ctrl+F3.

**Comment by mtrower** [comment]
_(btw, ctrl-f3 is system bound on macOS.  You need to go to System Preferences->Keyboard->Shortcuts->Keyboard and uncheck Move Focus to the Dock)_

@smoogipoo okay, here we go:
![Screen Shot 2020-06-30 at 15 31 08](https://user-images.githubusercontent.com/8810627/86174551-7a486d00-bae7-11ea-9fa3-a467ca32b2a3.png)

**Comment by smoogipoo** [comment]
@mtrower Ah I didn't realise your issue was just with videos according to your original issue, it's likely going to be a shader issue. What's your system specs - GPU / CPU?

**Comment by mtrower** [comment]
@smoogipoo i7-4770K / GTX 780

There's an integrated HD4600, but it isn't being used here.

Nvidia driver is... whatever's built into macOS (as is traditional).  I'm not certain, but I *think* it's 355.11.10.50.10.103

**Comment by smoogipoo** [comment]
@mtrower @cupppu @ryuKUNda can you all test and see if it's fixed in osu!'s latest release?

**Comment by cupppu** [comment]
No 2020.707.0 did not fix the artifacts

**Comment by mtrower** [comment]
Hi; sorry for the delay.  Neither 2020.707.0 nor 2020.712.0 resolve my situation.

**Comment by HinoTsume** [comment]
> _(btw, ctrl-f3 is system bound on macOS. You need to go to System Preferences->Keyboard->Shortcuts->Keyboard and uncheck Move Focus to the Dock)_
> 
> @smoogipoo okay, here we go: ![Screen Shot 2020-06-30 at 15 31 08](https://user-images.githubusercontent.com/8810627/86174551-7a486d00-bae7-11ea-9fa3-a467ca32b2a3.png)
![Screen Shot 2021-12-09 at 8 20 36 PM](https://user-images.githubusercontent.com/95862884/145404209-42aecf7c-ca9b-4ddc-96f5-b61b0c1b732e.png)

when i do that it shows up like this

**Comment by frenzibyte** [comment]
This has been reported once again in #19267 with GPU `NVIDIA GeForce 320M`:
```
2022-07-23 23:04:45 [verbose]: GL Initialized
2022-07-23 23:04:45 [verbose]: GL Version:                 2.1 NVIDIA-10.4.14 310.90.30.05b27
2022-07-23 23:04:45 [verbose]: GL Renderer:                NVIDIA GeForce 320M OpenGL Engine
2022-07-23 23:04:45 [verbose]: GL Shader Language version: 1.20
2022-07-23 23:04:45 [verbose]: GL Vendor:                  NVIDIA Corporation
```

**Comment by Exorix56** [comment]
Can anyone help me with the same problem?

**Comment by peppy** [comment]
Please wait a few weeks or months. We are working on a new renderer which should solve this.

**Comment by frenzibyte** [comment]
To begin with, can you reproduce this on Metal or is it only occurring on OpenGL?

**Comment by frenzibyte** [comment]
Seems like your only chance of figuring out a solution would be trial and error inside the `sh_TextureWrapping.h` file. The first thing I would try is removing the actual code that does wrapping, i.e.:
```diff
diff --git a/osu.Framework/Resources/Shaders/sh_Texture.fs b/osu.Framework/Resources/Shaders/sh_Texture.fs
index e93fe73b0..cc4401117 100644
--- a/osu.Framework/Resources/Shaders/sh_Texture.fs
+++ b/osu.Framework/Resources/Shaders/sh_Texture.fs
@@ -13,4 +13,4 @@ void main(void)
 {
     vec2 wrappedCoord = wrap(v_TexCoord, v_TexRect);
     o_Colour = getRoundedColor(wrappedSampler(wrappedCoord, v_TexRect, m_Texture, m_Sampler, -0.9), wrappedCoord);
-}
+}
\ No newline at end of file
```

And see how that behaves, to determine whether it's the GLSL functions returning weird values or there's something much weirder going on.

**Comment by Joehuu** [comment]
I removed those if statements when I had access, and is more or less the same behavior as my diff.

My diff:
`wrappedCoord = wrap(v_TexCoord, v_TexRect)` -> `v_TexCoord`

Your diff:
`wrappedCoord = wrap(v_TexCoord, v_TexRect)` = `wrap(float coord, int mode, float rangeMin, float rangeMax) => coord` = `v_TexCoord`

**Comment by frenzibyte** [comment]
Correct, but the results show that, seemingly, even if wrapping was disabled, text still get rendered incorrectly, so your diff shows that there's something definitely weird going on here and my diff tries to nail it down by trial-and-error.
